export { createRng, hashString, type Rng } from "./rng.js";
export {
  dayIndex,
  dayKey,
  EPOCH_MS,
  nextPuzzleAt,
  puzzleNumber,
  timeUntilNextPuzzle,
} from "./day.js";
export {
  buildMaze,
  GRID_HEIGHT,
  GRID_WIDTH,
  isPlayable,
  MAZE_COUNT,
  type Maze,
} from "./serpent/mazes.js";
export {
  ATTEMPTS_PER_DAY,
  cardFor,
  cardOf,
  compareCards,
  finalScore,
  MAX_PROMPT_CHARS,
  multiplierFor,
  PAR_CHARS,
  strokesOf,
  type GolfAttempt,
  type GolfCard,
} from "./golf/rules.js";
export {
  compareRuns,
  createGame,
  resultOf,
  seedForDay,
  step,
  tickIntervalMs,
  tierOf,
  turn,
  type DailyConfig,
  type Dir,
  type Point,
  type RunResult,
  type SerpentState,
  type Status,
} from "./serpent/engine.js";
export {
  advanceLevel,
  applyPowerUp,
  brickWorldX,
  brickWorldY,
  compareBreakoutRuns,
  createBreakout,
  fireLaser,
  nudgePaddle,
  releaseBall,
  resultOf as breakoutResultOf,
  setPaddleDir,
  spaceAction,
  step as stepBreakout,
  tickIntervalMs as breakoutTickIntervalMs,
  BRICK_VISUAL,
  BRICK_W as BREAKOUT_BRICK_W,
  FIELD_H as BREAKOUT_FIELD_H,
  FIELD_W as BREAKOUT_FIELD_W,
  LEVEL_COUNT as BREAKOUT_LEVEL_COUNT,
  PADDLE_BASE_W,
  PADDLE_Y,
  POWERUP_CATALOG,
  POWERUP_COUNT,
  POWERUP_TYPES,
  allLevels as allBreakoutLevels,
  difficultyOf as breakoutDifficultyOf,
  getLevel as getBreakoutLevel,
  type BreakoutRunResult,
  type BreakoutState,
  type BreakoutStatus,
  type Brick,
  type BrickKind,
  type PowerUpType,
} from "./breakout/engine.js";
